name: gphotos-uploader-cli
version: git
summary: A command line tool to upload to google photos
description: |
  gphotos-uploader-cli lets you mass upload folders of media to google photos.

grade: devel
confinement: devmode

parts:
  gphotos-uploader-cli:
    source: .
    plugin: go
    go-importpath: github.com/nmrshll/gphotos-uploader-cli

apps:
  gphotos-uploader:
    command: gphotos-uploader-cli